spring:
  application:
    name: TgBot

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=tg_bot;encrypt=true;trustServerCertificate=true;
    username: hradmin
    password: pasword
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: secret key
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000

telegram:
  bot:
    username: tg_bot
    token: key
